name: Skill-Loop CI

# الكود ده هيشتغل أوتوماتيك لما تعمل Push أو Pull Request على برانش الـ main
on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest # الروبوت هيشتغل على سيرفر لينكس سريع

steps:
  # 1. سحب الكود بتاعك
  - name: Checkout Code
    uses: actions/checkout@v4

  # 2. تسطيب بيئة دوت نت 10
  - name: Setup .NET 10
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: "10.0.x"

  # 3. تحميل المكتبات (مع تحديد ملف الـ Solution بالاسم)
  - name: Restore dependencies
    run: dotnet restore Skill-Loop.sln

  # 4. عمل بيلد للمشروع
  - name: Build
    run: dotnet build Skill-Loop.sln --configuration Release --no-restore

  # 5. تشغيل التستس
  - name: Test
    run: dotnet test Skill-Loop.sln --configuration Release --no-build --verbosity normal
